### ISSUE TITLE
Development build of game throws errors when user leaves page

### ISSUE THREAD

**Issue by bzh8205** [themolecularmoose/the-moose#13]
See above. May just be because of unity development web build.

**Comment by tlsteenWoo** [comment]
I build and ran a development web build.
I started at the menu, went to level select, then pressed space to go in game.
I then switched tabs and applications to 'leave the page'.
I did not notice any errors, are they logged somewhere, where did you notice them?
It seems it does not have this issue anymore, can you confirm?

**Comment by bzh8205** [comment]
This is an outdated bug, this should have been closed as it was for our semester one game.
